echo exporting public dir to a site dir, one dir up from the this file...
svn export --force public ..\site_%date:~-10,2%%date:~-7,2%%date:~-4,4%
echo exporting static dir to site dir, one dir up from the this file...
svn export --force static ..\site_%date:~-10,2%%date:~-7,2%%date:~-4,4%